wordpress:
  name: wordpress
  image: wordpress:4.8-apache
  containerPort: 80

service:
  type: NodePort
  port: 80

mysql:
  name: mysql
  image: mysql:5.6
  replicas: 1
  containerPort: 3306

services:
  type: ClusterIP
  port: 3306
