apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: {{.Values.services.port}}
  selector:
    app: wordpress
  type: {{.Values.services.type}}
